# Generated by Django 3.2.4 on 2021-06-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_cat',
            options={'verbose_name_plural': 'Item_Cats'},
        ),
    ]
